### ISSUE TITLE
Using messaging_service_sid with Twilio API integration

### ISSUE THREAD

**Issue by sergmetelin** [visualitypl/textris#10]
We should be able to use messaging_service_sid instead of :from to send the messages. Is there already a way to do it?

**Comment by karolsluszniak** [comment]
I think we could accommodate this with new setting that overrides `from` when used with Twilio delivery. The point is for texters to stay reusable across services that depend on from instead of sid.

**Comment by philnash** [comment]
I'm happy to take a look into this if you want?

**Comment by karolsluszniak** [comment]
:+1: It would consist of same steps as `media_urls`, ie. adding new texter/message field which I'd propose to prefix with service name if it's just for Twilio (so `twilio_messaging_service_sid` or `twilio_sid` if you think it describes it enough), tests, mail/log delivery and README.

**Comment by kmanzana** [comment]
Any update on this?  We need to use `messaging_service_sid`'s for our app.

**Comment by philnash** [comment]
Hey @kmanzana, I intended to try and do this, but I have not had the opportunity just yet. I can't promise a particular time that I will be able to get to it either.

You've got a couple of options with this.

* You can either take a crack at updating the library yourself, it should be relatively similar to adding media_urls as in [this pull request](https://github.com/visualitypl/textris/pull/14), but you'd need to affect number checking in the `Textris::Message` class
* You could forget Textris for now and use the [`twilio-ruby` gem](https://rubygems.org/gems/twilio-ruby) directly
* You could wait for me to finish it up 🙂

**Comment by kmanzana** [comment]
Thanks for the info @philnash.  I'm going to go ahead and take care of it now.  I assume you haven't started this yet.

**Comment by philnash** [comment]
I have not started this yet, so go for it!
