### ISSUE TITLE
Defaults don't get inherited from a base

### ISSUE THREAD

**Issue by halilim** [visualitypl/textris#11]
Defaults don't get inherited from a base:

``` ruby
class ApplicationTexter < Textris::Base
  default from: 'Acme Corp'
end
class SomethingTexter < ApplicationTexter
end

ApplicationTexter.with_defaults({}) # => {:from=>"Acme Corp"}
SomethingTexter.with_defaults({}) # => {}
```

I guess `class_attribute` can be used similar to how `ActionView::Layouts` implements `layout`? [`_layout` class attribute definition](https://github.com/rails/rails/blob/62b74d2b602b77989d5b6a9283877817bd82b44a/actionview/lib/action_view/layouts.rb#L207), [`layout` method](https://github.com/rails/rails/blob/62b74d2b602b77989d5b6a9283877817bd82b44a/actionview/lib/action_view/layouts.rb#L262)

**Comment by karolsluszniak** [comment]
:+1:
