### ISSUE TITLE
parse_content removes newlines

### ISSUE THREAD

**Issue by halilim** [visualitypl/textris#12]
`parse_content` is currently [removing](https://github.com/visualitypl/textris/blob/39023f150a70e8646511e12a55aad96df398f734/lib/textris/message.rb#L106) newlines. Newline is acceptable in an SMS message. Actually I don't think it's a responsibility of textris to do any transformation on the content.

**Comment by karolsluszniak** [comment]
Yeah, that was intentional. I assumed SMSes don't have newlines which seemed to be the case (?) in old days of mobiles.
