### ISSUE TITLE
Test against Rails 5

### ISSUE THREAD

**Issue by philnash** [visualitypl/textris#17]
Right now, due to the lock file being included, this will only run against Rails 4. We should test against Rails 5 and adjust CI so that tests can be run against both 4 and 5 for the time being.

**Comment by philnash** [comment]
Removing the requirement to pin rack at >1 and <2 and running the tests has lead to 3 failures. Seems promising.

**Comment by m-stachyra** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hmvr9HjW&#x2F;13-test-trello-s-github-powerup"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Test Trello&#39;s GitHub PowerUp!</a>
