### ISSUE TITLE
Shortcodes don't work

### ISSUE THREAD

**Issue by rylanb** [visualitypl/textris#25]
Hello,
 Great gem! I'm liking it so far. I'm curious if short codes are supported? I'm using this for a soon to launch app and getting this error: 

```Twilio::REST::RequestError: The 'From' number + is not a valid phone number, shortcode, or alphanumeric sender ID.```

When trying with 89045 format style of number as we have a short code we are trying to send messages from. Any thoughts or ideas here? 

I'd posit that phone_with_plus(phone) tries to add a + to it.

If I add a '+89045' I get the + error. If I try to pass in '89045' I get an error that the from is blank.

Any thoughts or guidance here? 

Thanks!

**Comment by philnash** [comment]
Hey @rylanb, I saw your issue and thought I'd try to fix it. Check out the PR in #26 and see whether that works for you.

**Comment by rylanb** [comment]
👍

**Comment by rylanb** [comment]
Testing on staging now and works locally pointing at your repo/branch.

**Comment by Marahin** [comment]
Closing the issue as https://github.com/visualitypl/textris/pull/39 is the successor of https://github.com/visualitypl/textris/pull/26 that will be included in the upcoming release.
