### ISSUE TITLE
Request: Ability to cancel/abort a send.

### ISSUE THREAD

**Issue by key88sf** [visualitypl/textris#30]
I couldn't find a good way of cancelling a send once a job has been queued. Rails mailers have a `self.message.perform_deliveries = false` flag which can be set on the message.

Basically what I'd like to do is have my code always queue the text jobs, but then when the job is actually performed in the background, be able to do some logic checks and prevent delivery of the message if some case is true. For example, if the job is running at 9am, do not send the text to people in area codes 818.

Any way of doing this easily?

**Comment by ronin** [comment]
@key88sf You can create explicit worker responsible for sending messages. And in this worker add your conditions for actually sending messages.

**Comment by nowakov** [comment]
Hey @key88sf, does ronin's answer solve your problem or you need further help?

**Comment by key88sf** [comment]
Yeah thanks :)
