### ISSUE TITLE
New version of twilio-ruby coming soon

### ISSUE THREAD

**Issue by philnash** [visualitypl/textris#33]
I just wanted to let you know that there is a new major version of the [twilio-ruby gem](https://github.com/twilio/twilio-ruby/) on it's way soon. This new version is not backwards compatible with version 4 or below.

Since Textris, in production, doesn't depend on twilio-ruby it is worth testing this with versions 3 (which is the development dependency here), 4 and 5 (currently rc18).

I can take a look at this soon, but things are really busy for me right now, so I thought I'd call it out here in case anyone else can look.

**Comment by nowakov** [comment]
Thanks a lot for a heads-up. I'll take a look at it next week and ping you if any doubts arise.
