### ISSUE TITLE
Alphanumeric support for Twilio

### ISSUE THREAD

**Issue by pskoike** [visualitypl/textris#34]
Hi!

Realy trying to use alphanumeric Id with Twilio and can't make it work. My quest is that Phony.normalize is passing just a + and not the string. Any thoughts?

**Comment by frodsan** [comment]
I think it's this https://github.com/visualitypl/textris/blob/master/lib/textris/delivery/twilio.rb#L20, having the same error.

**Comment by Marahin** [comment]
@pskoike @frodsan we're aiming to deliver both Alphanumeric ID and Short Codes in the upcoming release, there's a pull request: https://github.com/visualitypl/textris/pull/39
