### ISSUE TITLE
Twilio configuration

### ISSUE THREAD

**Issue by anamba** [visualitypl/textris#35]
Looks like this "pre-configuration" method no longer works in twilio-ruby 5.3.0:

Twilio.configure do |config|
  config.account_sid = 'some_sid'
  config.auth_token  = 'some_auth_token'
end

It was removed from lib/twilio-ruby.rb in this commit:
https://github.com/twilio/twilio-ruby/commit/038a3f921bb6ae66063389d9f685ab297042d06a

**Comment by philnash** [comment]
Twilio developer evangelist here.

I am investigating why this was removed from the gem and will report back when I know more.

**Comment by philnash** [comment]
The `configure` block has returned to the twilio-ruby gem in version 5.3.1. I am still investigating why it was removed.

**Comment by Lackoftactics** [comment]
@philnash any updates?

**Comment by philnash** [comment]
The `configure` block has returned and won't be removed again. Sadly this means that version 5.3.0 won't work with Textris, but the versions around it and continuing on in the future will.

I might recommend that the version constraint on the `twilio-ruby` gem moves up to `~> 5.4`. Although the versions are only development dependencies in this gem, so I'm not sure how much that will help.

**Comment by Marahin** [comment]
Since there hasn't been much activity since, I assume this has been resolved.
