### ISSUE TITLE
Publishing a new version?

### ISSUE THREAD

**Issue by MonsieurDart** [visualitypl/textris#45]
Hello guys,

Your Gem is great, very good idea and very cleanly done. 😉 

But would it be possible to publish a new version of the Gem? The [current 0.5.0 version](https://rubygems.org/gems/textris) does not contain some [recent and interesting additions for Nexmo](https://github.com/visualitypl/textris/commit/2cbfafb6b448e207c728aeb0aacbf421b25b75bc).

Thanks a lot!
Mathieu

**Comment by MonsieurDart** [comment]
By the way, if you need help to do the PR and Issues triage, let me know. 😊

**Comment by Marahin** [comment]
We're definitely open for looking up through PRs, so if you have any improvements that you'd like to publish here - please share! 

Sorry for keeping this issue open without any response for so long, we're trying to improve our OS maintaining strategy here at Visuality so hopefully the responses will be quicker in the future. :)

I'll be closing this PR as it doesn't contain that much activity, if you'd like to have a particular feature implemented please let us know in a new issue or Pull Request - best would be if you include description on why and which feature would you want to have in the library.

**Comment by MonsieurDart** [comment]
Thanks for your reply! 😊 

I was referring to the latest additions that cannot be used (see above) yet as there has not been any release for a while. Without an official new release, we cannot get the latest improvement from the Gem version of the library. 

Thanks again for your hard work.

**Comment by Marahin** [comment]
Ah, I get it now. I don't know why these changes haven't brough a version change.

Alright, this is something to think through, I'll probably bump the gem version to 0.6.0 and then release it. Sorry for inconvenience!

**Comment by MonsieurDart** [comment]
Génial ! Merci. 😉
